import type { IllustrationName } from '../../generated/illustrations';

/**
 * Extra search terms for the illustration Gallery, keyed by name. Aliases and
 * synonyms — not the name itself, which is always searchable — so an illustration
 * turns up even when you can't recall its exact name (e.g. "search" finds
 * `pic-magnifying-glass`, "fox" finds the mascot poses).
 *
 * Only illustrations that benefit from an alias need an entry.
 */
export const illustrationKeywords: Partial<Record<IllustrationName, string[]>> =
  {
    // Pictograms — semantic spot illustrations.
    'pic-blocks': ['building', 'stack', 'lego'],
    'pic-box': ['package', 'cube', 'parcel'],
    'pic-brackets-code': ['code', 'developer', 'programming', 'html'],
    'pic-browser-history-tabs': ['history', 'tabs'],
    'pic-browser-picture-in-picture': ['pip', 'video', 'floating'],
    'pic-browser-private': ['incognito', 'privacy', 'private browsing'],
    'pic-cursor': ['pointer', 'mouse', 'select'],
    'pic-devices': ['phone', 'laptop', 'sync', 'cross-device'],
    'pic-envelope-closed': ['email', 'mail', 'message'],
    'pic-envelope-open': ['email', 'mail', 'message', 'read'],
    'pic-eyedropper': ['color picker', 'sample', 'swatch'],
    'pic-fingerprint': ['privacy', 'tracking', 'biometric', 'identity'],
    'pic-globe': ['world', 'internet', 'web', 'language'],
    'pic-heart': ['love', 'like', 'favorite'],
    'pic-heart-sparkles': ['love', 'favorite', 'ai'],
    'pic-lightning-bolt': ['power', 'fast', 'energy', 'flash'],
    'pic-lock-closed': ['secure', 'privacy', 'password', 'locked'],
    'pic-lock-open': ['unlocked', 'insecure'],
    'pic-magnifying-glass': ['search', 'find', 'zoom', 'lookup'],
    'pic-pencil': ['edit', 'write', 'draw'],
    'pic-pencil-line': ['edit', 'write', 'draw', 'sign'],
    'pic-pin': ['tack', 'save', 'location', 'keep'],
    'pic-play-arrow': ['media', 'video', 'start', 'play'],
    'pic-puzzle': ['extension', 'addon', 'plugin'],
    'pic-shield': ['security', 'protect', 'privacy', 'guard'],
    'pic-shield-alert': ['security', 'warning', 'privacy'],
    'pic-shield-checkmark': ['security', 'protected', 'safe'],
    'pic-shield-error': ['security', 'danger', 'critical'],
    'pic-sparkles-ai': ['ai', 'magic', 'generate', 'shine'],
    'pic-star': ['favorite', 'rating', 'bookmark'],
    'pic-star-flame': ['favorite', 'hot', 'trending'],
    'pic-sync-arrows': ['refresh', 'reload', 'sync'],
    'pic-toggle-on': ['switch', 'setting', 'enabled'],
    'pic-translation-language': ['translate', 'i18n', 'locale', 'language'],

    // Kit — the fox mascot and reusable scene pieces.
    'kit-closeup-cautious': ['fox', 'mascot', 'character', 'worried'],
    'kit-closeup-cautious-hole': ['fox', 'mascot', 'character'],
    'kit-closeup-look-forward': ['fox', 'mascot', 'character'],
    'kit-closeup-look-up': ['fox', 'mascot', 'character'],
    'kit-cover-eyes': ['fox', 'mascot', 'character', 'hide'],
    'kit-face-small': ['fox', 'mascot', 'character'],
    'kit-hero-sit-look-forward': ['fox', 'mascot', 'character', 'hero'],
    'kit-hero-sit-look-side': ['fox', 'mascot', 'character', 'hero'],
    'kit-hero-sit-look-up': ['fox', 'mascot', 'character', 'hero'],
    'kit-sit-head-tilt': ['fox', 'mascot', 'character'],
    'kit-sit-profile': ['fox', 'mascot', 'character'],
    'kit-sit-profile-tail': ['fox', 'mascot', 'character'],
    'kit-sleep-inactive': ['fox', 'mascot', 'idle', 'rest'],
    'kit-sleep-laptop': ['fox', 'mascot', 'idle', 'rest'],
    'kit-sleep-lock-chest': ['fox', 'mascot', 'idle', 'rest'],
    'kit-sleeping-curled': ['fox', 'mascot', 'idle', 'rest'],
    'kit-run-1': ['fox', 'mascot', 'motion', 'running'],
    'kit-run-2': ['fox', 'mascot', 'motion', 'running'],
    'kit-run-3': ['fox', 'mascot', 'motion', 'running'],
    'kit-run-4': ['fox', 'mascot', 'motion', 'running'],
    'kit-walking': ['fox', 'mascot', 'motion'],
    'kit-walk-portal': ['fox', 'mascot', 'motion'],
    'kit-glide': ['fox', 'mascot', 'motion'],
    'kit-glide-ai': ['fox', 'mascot', 'ai', 'magic'],
    'kit-meditate-clouds': ['fox', 'mascot', 'calm', 'relax', 'zen'],
    'kit-hold-heart': ['fox', 'mascot', 'love', 'favorite'],
    'kit-hold-lock': ['fox', 'mascot', 'secure', 'privacy'],
    'kit-hold-icons': ['fox', 'mascot'],
    'kit-heart-curled': ['love', 'favorite'],
    'kit-paw': ['fox', 'pet', 'animal', 'footprint'],
    'kit-lever-closeup-paw': ['fox', 'pet', 'animal'],
    'kit-house': ['home'],
    'kit-keyhole': ['lock', 'security', 'privacy'],
    'kit-shield': ['security', 'protect', 'privacy'],
    'kit-sparkle-ai': ['ai', 'magic', 'generate'],
    'kit-puzzle-extensions-add-ons': ['extension', 'addon', 'plugin'],
    'kit-tab-groups': ['tabs', 'group'],
    'kit-tail-folder-bookmarks': ['folder', 'bookmarks'],
    'kit-tail-folder-downloads': ['folder', 'downloads'],
    'kit-shake-trackers-cursors': ['privacy', 'tracking', 'trackers'],
    'kit-headphones-listen': ['audio', 'music', 'podcast', 'listen'],
    'kit-fly-airplane': ['plane', 'travel', 'flight'],
    'kit-butterflies': ['nature', 'insects'],
    'kit-grass': ['nature', 'plant'],
    'kit-rock': ['nature', 'stone'],
    'kit-devices-sync': ['phone', 'laptop', 'sync'],
    'kit-devices-sync-error': ['phone', 'laptop', 'sync', 'error'],
    'kit-plug-error': ['plugin', 'error', 'disconnected'],
    'kit-toggle': ['switch', 'setting'],
    'kit-checkmark': ['done', 'complete', 'success'],
  };
