// Idiomatic CSS declaration order (https://github.com/necolas/idiomatic-css#declaration-order):
// positioning → box model → typography → visual. Extended to cover the logical
// properties this codebase uses; anything unlisted sorts alphabetically at the
// end of its block. All rules here are auto-fixable via `npm run format`.

/** @type {import('stylelint').Config} */
export default {
  plugins: ['stylelint-order'],
  rules: {
    'order/properties-order': [
      [
        // Positioning
        'position',
        'z-index',
        'inset',
        'inset-block',
        'inset-block-start',
        'inset-block-end',
        'inset-inline',
        'inset-inline-start',
        'inset-inline-end',
        'top',
        'right',
        'bottom',
        'left',

        // Box model: display & flow
        'box-sizing',
        'display',
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'flex-direction',
        'flex-flow',
        'flex-wrap',
        'grid',
        'grid-template',
        'grid-template-columns',
        'grid-template-rows',
        'grid-template-areas',
        'grid-area',
        'grid-column',
        'grid-row',
        'grid-auto-flow',
        'grid-auto-columns',
        'grid-auto-rows',
        'place-items',
        'place-content',
        'place-self',
        'align-items',
        'align-content',
        'align-self',
        'justify-items',
        'justify-content',
        'justify-self',
        'order',
        'gap',
        'row-gap',
        'column-gap',
        'float',
        'clear',
        'overflow',
        'overflow-x',
        'overflow-y',
        'overflow-block',
        'overflow-inline',

        // Box model: sizing
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'inline-size',
        'min-inline-size',
        'max-inline-size',
        'block-size',
        'min-block-size',
        'max-block-size',

        // Box model: margin
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'margin-block',
        'margin-block-start',
        'margin-block-end',
        'margin-inline',
        'margin-inline-start',
        'margin-inline-end',

        // Box model: padding
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'padding-block',
        'padding-block-start',
        'padding-block-end',
        'padding-inline',
        'padding-inline-start',
        'padding-inline-end',

        // Box model: border & outline
        'border',
        'border-width',
        'border-style',
        'border-color',
        'border-top',
        'border-right',
        'border-bottom',
        'border-left',
        'border-block',
        'border-block-start',
        'border-block-end',
        'border-inline',
        'border-inline-start',
        'border-inline-end',
        'border-radius',
        'outline',
        'outline-width',
        'outline-style',
        'outline-color',
        'outline-offset',

        // Typography
        'color',
        'font',
        'font-family',
        'font-size',
        'font-weight',
        'font-style',
        'line-height',
        'letter-spacing',
        'text-align',
        'text-transform',
        'text-decoration',
        'text-overflow',
        'white-space',
        'word-break',
        'vertical-align',
        'list-style',

        // Visual & other
        'background',
        'background-color',
        'background-image',
        'background-position',
        'background-size',
        'background-repeat',
        'box-shadow',
        'opacity',
        'visibility',
        'filter',
        'backdrop-filter',
        'mix-blend-mode',
        'color-scheme',
        'accent-color',
        'transition',
        'transform',
        'transform-origin',
        'animation',
        'will-change',
        'content',
        'cursor',
        'pointer-events',
        'user-select',
        'touch-action',
        'appearance',
        'resize',
      ],
      { unspecified: 'bottomAlphabetical' },
    ],

    // Consistent blank lines between blocks.
    'rule-empty-line-before': [
      'always',
      { except: ['first-nested'], ignore: ['after-comment'] },
    ],
    'at-rule-empty-line-before': [
      'always',
      { except: ['first-nested'], ignore: ['after-comment'] },
    ],
    'comment-empty-line-before': ['always', { except: ['first-nested'] }],
  },
  ignoreFiles: [
    'src/generated/**',
    'dist/**',
    'storybook-static/**',
    'coverage/**',
    'node_modules/**',
    'vendor/**',
  ],
};
