import type { IconName } from '../../generated/icons';

/**
 * Extra search terms for the icon Gallery, keyed by icon name. These are aliases
 * and synonyms — not the name itself, which is always searchable — so an icon
 * turns up even when you can't recall its exact name (e.g. "trash" finds
 * `delete`, "magnifying glass" finds `search`).
 *
 * Only icons that benefit from an alias need an entry; the rest are found by name.
 */
export const iconKeywords: Partial<Record<IconName, string[]>> = {
  accessibility: ['a11y', 'wheelchair', 'disability'],
  activity: ['pulse', 'graph', 'chart', 'stats'],
  add: ['plus', 'new', 'create'],
  'add-circle-fill': ['plus', 'new', 'create'],
  'add-text': ['text', 'insert', 'plus'],
  'add-user': ['person', 'invite', 'member', 'plus'],
  airplane: ['flight', 'travel', 'airport', 'plane'],
  plane: ['flight', 'travel', 'airport', 'airplane'],
  'all-tabs': ['tabs', 'overview'],
  'app-menu': ['hamburger', 'menu', 'more', 'kebab'],
  apple: ['mac', 'ios', 'macos'],
  archive: ['box', 'store'],
  'arrow-clockwise': ['refresh', 'redo', 'reload', 'rotate'],
  'arrow-counterclockwise': ['undo', 'rotate', 'back'],
  ask: ['question', 'chat', 'prompt'],
  audio: ['sound', 'speaker', 'volume'],
  'audio-smaller': ['sound', 'speaker', 'volume'],
  'audio-muted': ['mute', 'silent', 'volume off', 'no sound'],
  'audio-muted-smaller': ['mute', 'silent', 'volume off', 'no sound'],
  'authenticated-user': ['signed in', 'login', 'account'],
  'unauthenticated-user': ['signed out', 'logout', 'account'],
  autoplay: ['auto', 'play'],
  'autoplay-slash': ['auto', 'play', 'off'],
  'avatar-signed-in-fill': ['account', 'profile', 'user'],
  'avatar-signed-out': ['account', 'profile', 'user'],
  back: ['previous', 'arrow left', 'return'],
  'back-small': ['previous', 'arrow left', 'return'],
  barbell: ['gym', 'weight', 'fitness', 'exercise', 'workout'],
  baseball: ['sport', 'ball'],
  basketball: ['sport', 'ball'],
  football: ['sport', 'ball'],
  'soccer-ball': ['sport', 'ball', 'football'],
  hockey: ['sport'],
  golf: ['sport'],
  cricket: ['sport'],
  racing: ['sport', 'motorsport', 'car'],
  bike: ['bicycle', 'cycling'],
  block: ['ban', 'prohibited', 'no', 'forbidden'],
  'blocked-popup': ['popup', 'ad'],
  book: ['read', 'manual', 'guide'],
  bookmark: ['save', 'favorite', 'star'],
  'bookmark-fill': ['save', 'favorite', 'star'],
  'bookmarks-tray': ['bookmarks', 'favorites'],
  briefcase: ['work', 'job', 'business'],
  calendar: ['date', 'schedule', 'event'],
  camera: ['photo', 'webcam'],
  'camera-slash': ['photo', 'webcam', 'off'],
  canvas: ['drawing', 'draw'],
  'chat-history': ['messages', 'conversation'],
  checkmark: ['check', 'done', 'tick', 'complete', 'yes', 'success'],
  'checkmark-circle-fill': ['check', 'done', 'complete', 'success', 'yes'],
  'double-checkmark': ['check', 'done', 'read', 'delivered'],
  'chevron-down': ['arrow', 'expand', 'caret'],
  'chevron-up': ['arrow', 'collapse', 'caret'],
  'chevron-left': ['arrow', 'previous', 'caret'],
  'chevron-right': ['arrow', 'next', 'caret'],
  close: ['x', 'cancel', 'dismiss', 'exit'],
  'close-circle-fill': ['x', 'cancel', 'dismiss'],
  'closed-caption': ['subtitles', 'cc'],
  'color-picker': ['eyedropper', 'palette', 'swatch'],
  comment: ['chat', 'message', 'feedback', 'speech bubble'],
  copy: ['duplicate', 'clipboard'],
  critical: ['error', 'danger', 'alert'],
  'critical-fill': ['error', 'danger', 'alert'],
  cryptominer: ['crypto', 'mining', 'bitcoin'],
  'cursor-arrow': ['pointer', 'mouse', 'select'],
  dashboard: ['overview', 'panel', 'gauge'],
  'data-clearance': ['privacy', 'clear data'],
  delete: ['trash', 'remove', 'bin', 'garbage', 'discard'],
  'device-mobile': ['phone', 'smartphone', 'mobile'],
  diamond: ['gem', 'premium'],
  dog: ['pet', 'animal', 'puppy'],
  'paw-print': ['pet', 'animal', 'dog', 'cat'],
  'dollar-sign-circle': ['money', 'cost', 'currency', 'usd'],
  price: ['money', 'cost', 'tag'],
  'payment-methods': ['card', 'credit card', 'pay'],
  'shopping-cart': ['buy', 'purchase', 'cart', 'store'],
  shopping: ['buy', 'purchase', 'bag', 'store'],
  'download-progress': ['save', 'get'],
  'downloaded-file': ['save', 'get'],
  downloads: ['save', 'get'],
  edit: ['pencil', 'write', 'modify', 'change'],
  'edit-active': ['pencil', 'write', 'modify'],
  'edit-squiggle': ['pencil', 'write', 'modify'],
  email: ['mail', 'envelope', 'message'],
  'email-mask': ['mail', 'relay', 'privacy'],
  'email-shield': ['mail', 'protect', 'privacy'],
  error: ['warning', 'alert', 'problem'],
  'error-fill': ['warning', 'alert', 'problem'],
  experiments: ['beta', 'flask', 'test', 'lab'],
  labs: ['beta', 'flask', 'test', 'experiment'],
  'export-data': ['transfer', 'share', 'out'],
  'import-data': ['transfer', 'load', 'in'],
  'import-export': ['transfer', 'sync'],
  extension: ['addon', 'plugin', 'puzzle'],
  'extension-fill': ['addon', 'plugin', 'puzzle'],
  'external-link': ['open', 'new window', 'link out'],
  filter: ['funnel', 'refine', 'sort'],
  'find-in-page': ['search', 'find', 'lookup'],
  fingerprinter: ['tracking', 'privacy', 'fingerprint'],
  'firefox-bridge': ['firefox', 'mozilla'],
  'firefox-browser-bridge': ['firefox', 'mozilla'],
  flower: ['nature', 'plant', 'bloom'],
  leaf: ['nature', 'plant', 'eco'],
  tree: ['nature', 'plant', 'forest'],
  folder: ['directory', 'file'],
  'folder-fill': ['directory', 'file'],
  'folder-arrow-down': ['directory', 'download', 'save'],
  footprints: ['tracking', 'steps'],
  forward: ['next', 'arrow right'],
  'forward-small': ['next', 'arrow right'],
  'fullscreen-expand': ['maximize', 'enlarge', 'screen'],
  'fullscreen-exit': ['minimize', 'screen'],
  'fx-view': ['firefox view'],
  gift: ['present', 'reward'],
  'gift-box': ['present', 'reward'],
  glasses: ['reader', 'read', 'view'],
  globe: ['world', 'internet', 'web', 'network', 'language'],
  'globe-slash': ['world', 'internet', 'web', 'offline'],
  'globe-warning': ['world', 'internet', 'web', 'insecure'],
  hammer: ['build', 'tool', 'fix', 'repair'],
  hand: ['stop', 'wave', 'raise'],
  heart: ['like', 'love', 'favorite'],
  'heart-rate': ['health', 'pulse', 'bpm'],
  help: ['question', 'support', 'faq'],
  'help-fill': ['question', 'support', 'faq'],
  highlighter: ['marker', 'pen', 'highlight'],
  history: ['recent', 'clock', 'time', 'past'],
  home: ['house', 'start', 'main'],
  identity: ['profile', 'id', 'account'],
  information: ['info', 'about', 'details'],
  'information-fill': ['info', 'about', 'details'],
  'justify-center': ['align', 'text', 'format'],
  'justify-left': ['align', 'text', 'format'],
  'justify-right': ['align', 'text', 'format'],
  'letter-spacing': ['text', 'typography', 'kerning'],
  'line-spacing': ['text', 'typography', 'leading'],
  'word-spacing': ['text', 'typography'],
  keyboard: ['type', 'input', 'keys'],
  'knife-and-fork': ['food', 'restaurant', 'eat', 'dining'],
  languages: ['language', 'locale', 'translation', 'i18n'],
  translate: ['language', 'translation', 'i18n'],
  'translations-companion': ['language', 'translation', 'i18n'],
  layer: ['stack', 'layers'],
  library: ['books', 'collection'],
  lightbulb: ['idea', 'tip', 'hint'],
  'lightning-bolt': ['power', 'energy', 'fast', 'flash'],
  link: ['url', 'chain', 'hyperlink'],
  list: ['menu', 'items', 'bullets'],
  'local-host': ['network', 'server', 'localhost'],
  'local-network': ['network', 'server', 'lan'],
  location: ['map', 'pin', 'gps', 'place', 'geolocation'],
  'location-slash': ['map', 'pin', 'gps', 'off'],
  lock: ['secure', 'security', 'private', 'password', 'encrypted', 'https'],
  'lock-slash': ['insecure', 'unlocked', 'http'],
  'lock-document': ['secure', 'private', 'encrypted'],
  'lock-warning': ['insecure', 'security'],
  login: ['signin', 'enter', 'authenticate'],
  off: ['power', 'logout', 'shutdown', 'exit'],
  'organizational-unit': ['office', 'enterprise', 'business'],
  makeup: ['beauty', 'cosmetics'],
  memories: ['photos', 'gallery', 'album'],
  microphone: ['mic', 'record', 'voice', 'audio'],
  'microphone-slash': ['mic', 'mute', 'voice off'],
  midi: ['music', 'instrument', 'piano'],
  move: ['drag', 'reposition', 'arrows'],
  'musical-note': ['music', 'song', 'audio'],
  'new-chat': ['message', 'conversation', 'compose'],
  newsfeed: ['news', 'feed', 'articles'],
  notifications: ['bell', 'alert', 'reminder'],
  'notifications-slash': ['bell', 'mute', 'silent'],
  'notification-fill': ['bell', 'alert', 'reminder'],
  palette: ['color', 'paint', 'theme', 'swatch'],
  paperclip: ['attach', 'attachment', 'clip'],
  passkey: ['key', 'password', 'login', 'credential'],
  'pause-fill': ['media', 'control', 'stop'],
  'play-fill': ['media', 'control', 'start'],
  'play-circle-fill': ['media', 'control', 'start'],
  'stop-fill': ['media', 'control', 'halt'],
  permission: ['access', 'allow'],
  'picture-in-picture-open': ['pip', 'video', 'floating'],
  'picture-in-picture-closed': ['pip', 'video', 'floating'],
  pin: ['tack', 'save', 'keep'],
  'pin-fill': ['tack', 'save', 'keep'],
  'playback-forward': ['media', 'skip', 'fast forward'],
  'playback-rewind': ['media', 'skip', 'rewind'],
  'playback-speed': ['media', 'rate', 'tempo'],
  plugin: ['addon', 'extension', 'puzzle'],
  policy: ['rules', 'document', 'terms'],
  'presentation-mode': ['slides', 'present', 'projector'],
  print: ['printer'],
  'private-mode-fill': ['incognito', 'private browsing', 'mask'],
  'private-mode-circle-fill': ['incognito', 'private browsing', 'mask'],
  'qr-code': ['barcode', 'scan'],
  quality: ['star', 'rating'],
  'reader-mode': ['read', 'article'],
  'remove-user': ['delete user', 'person', 'kick'],
  restore: ['undo', 'revert', 'recover'],
  routed: ['vpn', 'network', 'proxy'],
  'routed-slash': ['vpn', 'network', 'proxy', 'off'],
  screenshare: ['capture', 'screen', 'share'],
  'screenshare-slash': ['capture', 'screen', 'stop'],
  screenshot: ['capture', 'screen', 'grab'],
  search: ['find', 'magnifier', 'magnifying glass', 'lookup', 'query'],
  'search-in-circle': ['find', 'magnifier', 'lookup'],
  'search-tabs': ['find', 'tabs', 'lookup'],
  settings: ['gear', 'preferences', 'options', 'config', 'cog'],
  'share-macos': ['share', 'export'],
  'share-winos': ['share', 'export'],
  shield: ['security', 'protect', 'privacy', 'guard', 'defense'],
  'shield-checkmark': ['security', 'protected', 'safe'],
  'shield-slash': ['security', 'unprotected', 'off'],
  shipping: ['delivery', 'truck', 'package'],
  'show-password': ['eye', 'visibility', 'reveal', 'view'],
  'show-password-slash': ['eye', 'hide', 'hidden'],
  'sidebar-left': ['panel', 'layout', 'drawer'],
  'sidebar-right': ['panel', 'layout', 'drawer'],
  'sidebar-hidden': ['panel', 'layout', 'collapse'],
  signature: ['sign', 'autograph'],
  'single-user': ['person', 'account', 'profile', 'member'],
  users: ['people', 'accounts', 'members', 'group', 'team'],
  'skip-backward': ['media', 'previous', 'rewind'],
  'skip-forward': ['media', 'next'],
  'social-tracker': ['tracking', 'privacy', 'social media'],
  sort: ['order', 'arrange'],
  'sparkle-single': ['ai', 'magic', 'shine', 'generate'],
  sparkles: ['ai', 'magic', 'shine', 'stars', 'generate'],
  'split-view': ['layout', 'panel', 'columns'],
  stocks: ['finance', 'chart', 'market', 'trading'],
  storage: ['disk', 'database', 'save'],
  'storage-slash': ['disk', 'database', 'off'],
  subtract: ['minus', 'remove', 'delete'],
  'subtract-circle-fill': ['minus', 'remove', 'delete'],
  sun: ['theme', 'light', 'day', 'brightness'],
  moon: ['theme', 'dark', 'night'],
  'swap-horizontal': ['switch', 'exchange', 'transfer'],
  sync: ['refresh', 'reload', 'update'],
  'synced-tabs': ['refresh', 'tabs'],
  update: ['refresh', 'reload', 'upgrade'],
  'update-circle': ['refresh', 'reload', 'upgrade'],
  tab: ['browser tab'],
  'tab-group': ['browser tabs', 'group'],
  'text-cursor': ['caret', 'type', 'insert'],
  themes: ['appearance', 'color', 'skin'],
  'thumbs-up': ['like', 'vote', 'approve', 'feedback'],
  'thumbs-down': ['dislike', 'vote', 'reject', 'feedback'],
  'top-sites': ['bookmarks', 'frequent', 'favorites'],
  'tracking-cookies': ['privacy', 'cookies', 'tracker'],
  'video-game-controller': ['game', 'gaming', 'gamepad', 'console'],
  'vpn-on': ['network', 'privacy', 'connected'],
  'vpn-off': ['network', 'privacy', 'disconnected'],
  'vpn-disconnected': ['network', 'privacy', 'offline'],
  warning: ['alert', 'caution', 'error'],
  'warning-fill': ['alert', 'caution', 'error'],
  webserial: ['serial', 'port'],
  weather: ['nature', 'forecast', 'cloud'],
  window: ['browser'],
  'window-firefox': ['browser', 'firefox'],
  xr: ['vr', 'ar', 'virtual reality', 'augmented reality'],
  'xr-slash': ['vr', 'ar', 'off'],
};
